stages:
  - build
  - test
  - release

build:
  stage: build
  script: sbt clean compile  
  tags:
    - build-in-docker
    - cs-eco-builder

test:
  stage: test
  script:
    - sbt test
  tags:
    - build-in-docker
    - cs-eco-builder

test-release:
  stage: release
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - sbt -Ddocker.tag=$CI_COMMIT_REF_NAME dockerBuildAndPush
  except:
    - master
    - develop
  tags:
    - build-as-docker
    - cs-eco-builder

release:
  stage: release
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - sbt dockerBuildAndPush
  only:
    - master
    - develop
  tags:
    - build-as-docker
    - cs-eco-builder

