version: '3.3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.4"
    environment:
      - cluster.name=cs-kv-storage-compose
      - discovery.type=single-node
      - discovery.zen.minimum_master_nodes=1
      - network.host=0.0.0.0
      - xpack.security.enabled=false
    volumes:
      - eslogs:/usr/share/elasticsearch/logs
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow"]
      interval: 60s
      timeout: 30s
      retries: 2
    networks:
      - cs-kv-storage-e2e
  initializer:
    build: ./initializer
    depends_on:
      - elasticsearch
    networks:
      - cs-kv-storage-e2e
  app:
    image: "git.bw-sw.com:5000/cloudstack-ecosystem/cs-kv-storage:${APP_DOCKER_TAG}"
    depends_on:
      - initializer
    volumes:
      - applogs:/var/log/cs-kv-storage
      - "./cs-kv-storage/application.conf:/opt/cs-kv-storage/application.conf"
    networks:
      - cs-kv-storage-e2e
  newman:
    image: "postman/newman_ubuntu1404"
    volumes:
      - ./newman:/etc/newman
    networks:
      - cs-kv-storage-e2e
volumes:
  eslogs:
  esdata:
  applogs:
networks:
  cs-kv-storage-e2e:
